/**
 * Códigos de país (DDI/E.164), ordenados numericamente pelo DDI, com
 * o Brasil sempre primeiro (é o default do select). Alguns
 * territórios pequenos compartilham código com o país "principal"
 * (ex.: vários caribenhos usam +1, Cazaquistão usa +7 como a Rússia)
 * — de propósito mantemos só uma entrada por código pra cada
 * `codigo` ser único na lista (importante pro round-trip de
 * extrairDdiENumero ao reabrir um telefone já salvo).
 */
export const DDIS: { codigo: string; pais: string }[] = [
  { codigo: "55", pais: "Brasil" },
  { codigo: "1", pais: "Canadá/EUA" },
  { codigo: "7", pais: "Rússia" },
  { codigo: "20", pais: "Egito" },
  { codigo: "27", pais: "África do Sul" },
  { codigo: "30", pais: "Grécia" },
  { codigo: "31", pais: "Países Baixos" },
  { codigo: "32", pais: "Bélgica" },
  { codigo: "33", pais: "França" },
  { codigo: "34", pais: "Espanha" },
  { codigo: "36", pais: "Hungria" },
  { codigo: "39", pais: "Itália" },
  { codigo: "40", pais: "Romênia" },
  { codigo: "41", pais: "Suíça" },
  { codigo: "43", pais: "Áustria" },
  { codigo: "44", pais: "Reino Unido" },
  { codigo: "45", pais: "Dinamarca" },
  { codigo: "46", pais: "Suécia" },
  { codigo: "47", pais: "Noruega" },
  { codigo: "48", pais: "Polônia" },
  { codigo: "49", pais: "Alemanha" },
  { codigo: "51", pais: "Peru" },
  { codigo: "52", pais: "México" },
  { codigo: "53", pais: "Cuba" },
  { codigo: "54", pais: "Argentina" },
  { codigo: "56", pais: "Chile" },
  { codigo: "57", pais: "Colômbia" },
  { codigo: "58", pais: "Venezuela" },
  { codigo: "60", pais: "Malásia" },
  { codigo: "61", pais: "Austrália" },
  { codigo: "62", pais: "Indonésia" },
  { codigo: "63", pais: "Filipinas" },
  { codigo: "64", pais: "Nova Zelândia" },
  { codigo: "65", pais: "Singapura" },
  { codigo: "66", pais: "Tailândia" },
  { codigo: "81", pais: "Japão" },
  { codigo: "82", pais: "Coreia do Sul" },
  { codigo: "84", pais: "Vietnã" },
  { codigo: "86", pais: "China" },
  { codigo: "90", pais: "Turquia" },
  { codigo: "91", pais: "Índia" },
  { codigo: "92", pais: "Paquistão" },
  { codigo: "93", pais: "Afeganistão" },
  { codigo: "94", pais: "Sri Lanka" },
  { codigo: "95", pais: "Mianmar" },
  { codigo: "98", pais: "Irã" },
  { codigo: "211", pais: "Sudão do Sul" },
  { codigo: "212", pais: "Marrocos" },
  { codigo: "213", pais: "Argélia" },
  { codigo: "216", pais: "Tunísia" },
  { codigo: "218", pais: "Líbia" },
  { codigo: "220", pais: "Gâmbia" },
  { codigo: "221", pais: "Senegal" },
  { codigo: "222", pais: "Mauritânia" },
  { codigo: "223", pais: "Mali" },
  { codigo: "224", pais: "Guiné" },
  { codigo: "225", pais: "Costa do Marfim" },
  { codigo: "226", pais: "Burkina Faso" },
  { codigo: "227", pais: "Níger" },
  { codigo: "228", pais: "Togo" },
  { codigo: "229", pais: "Benin" },
  { codigo: "230", pais: "Maurício" },
  { codigo: "231", pais: "Libéria" },
  { codigo: "232", pais: "Serra Leoa" },
  { codigo: "233", pais: "Gana" },
  { codigo: "234", pais: "Nigéria" },
  { codigo: "235", pais: "Chade" },
  { codigo: "236", pais: "República Centro-Africana" },
  { codigo: "237", pais: "Camarões" },
  { codigo: "238", pais: "Cabo Verde" },
  { codigo: "239", pais: "São Tomé e Príncipe" },
  { codigo: "240", pais: "Guiné Equatorial" },
  { codigo: "241", pais: "Gabão" },
  { codigo: "242", pais: "Congo" },
  { codigo: "243", pais: "República Democrática do Congo" },
  { codigo: "244", pais: "Angola" },
  { codigo: "245", pais: "Guiné-Bissau" },
  { codigo: "248", pais: "Seychelles" },
  { codigo: "249", pais: "Sudão" },
  { codigo: "250", pais: "Ruanda" },
  { codigo: "251", pais: "Etiópia" },
  { codigo: "252", pais: "Somália" },
  { codigo: "253", pais: "Djibuti" },
  { codigo: "254", pais: "Quênia" },
  { codigo: "255", pais: "Tanzânia" },
  { codigo: "256", pais: "Uganda" },
  { codigo: "257", pais: "Burundi" },
  { codigo: "258", pais: "Moçambique" },
  { codigo: "260", pais: "Zâmbia" },
  { codigo: "261", pais: "Madagascar" },
  { codigo: "263", pais: "Zimbábue" },
  { codigo: "264", pais: "Namíbia" },
  { codigo: "265", pais: "Malawi" },
  { codigo: "266", pais: "Lesoto" },
  { codigo: "267", pais: "Botsuana" },
  { codigo: "268", pais: "Essuatíni" },
  { codigo: "269", pais: "Comores" },
  { codigo: "291", pais: "Eritreia" },
  { codigo: "350", pais: "Gibraltar" },
  { codigo: "351", pais: "Portugal" },
  { codigo: "352", pais: "Luxemburgo" },
  { codigo: "353", pais: "Irlanda" },
  { codigo: "354", pais: "Islândia" },
  { codigo: "355", pais: "Albânia" },
  { codigo: "356", pais: "Malta" },
  { codigo: "357", pais: "Chipre" },
  { codigo: "358", pais: "Finlândia" },
  { codigo: "359", pais: "Bulgária" },
  { codigo: "370", pais: "Lituânia" },
  { codigo: "371", pais: "Letônia" },
  { codigo: "372", pais: "Estônia" },
  { codigo: "373", pais: "Moldávia" },
  { codigo: "374", pais: "Armênia" },
  { codigo: "375", pais: "Bielorrússia" },
  { codigo: "376", pais: "Andorra" },
  { codigo: "377", pais: "Mônaco" },
  { codigo: "378", pais: "São Marino" },
  { codigo: "380", pais: "Ucrânia" },
  { codigo: "381", pais: "Sérvia" },
  { codigo: "382", pais: "Montenegro" },
  { codigo: "385", pais: "Croácia" },
  { codigo: "386", pais: "Eslovênia" },
  { codigo: "387", pais: "Bósnia e Herzegovina" },
  { codigo: "389", pais: "Macedônia do Norte" },
  { codigo: "420", pais: "República Tcheca" },
  { codigo: "421", pais: "Eslováquia" },
  { codigo: "423", pais: "Liechtenstein" },
  { codigo: "501", pais: "Belize" },
  { codigo: "502", pais: "Guatemala" },
  { codigo: "503", pais: "El Salvador" },
  { codigo: "504", pais: "Honduras" },
  { codigo: "505", pais: "Nicarágua" },
  { codigo: "506", pais: "Costa Rica" },
  { codigo: "507", pais: "Panamá" },
  { codigo: "509", pais: "Haiti" },
  { codigo: "591", pais: "Bolívia" },
  { codigo: "592", pais: "Guiana" },
  { codigo: "593", pais: "Equador" },
  { codigo: "595", pais: "Paraguai" },
  { codigo: "597", pais: "Suriname" },
  { codigo: "598", pais: "Uruguai" },
  { codigo: "670", pais: "Timor-Leste" },
  { codigo: "673", pais: "Brunei" },
  { codigo: "675", pais: "Papua-Nova Guiné" },
  { codigo: "676", pais: "Tonga" },
  { codigo: "678", pais: "Vanuatu" },
  { codigo: "679", pais: "Fiji" },
  { codigo: "680", pais: "Palau" },
  { codigo: "685", pais: "Samoa" },
  { codigo: "850", pais: "Coreia do Norte" },
  { codigo: "852", pais: "Hong Kong" },
  { codigo: "853", pais: "Macau" },
  { codigo: "855", pais: "Camboja" },
  { codigo: "856", pais: "Laos" },
  { codigo: "880", pais: "Bangladesh" },
  { codigo: "886", pais: "Taiwan" },
  { codigo: "960", pais: "Maldivas" },
  { codigo: "961", pais: "Líbano" },
  { codigo: "962", pais: "Jordânia" },
  { codigo: "963", pais: "Síria" },
  { codigo: "964", pais: "Iraque" },
  { codigo: "965", pais: "Kuwait" },
  { codigo: "966", pais: "Arábia Saudita" },
  { codigo: "967", pais: "Iêmen" },
  { codigo: "968", pais: "Omã" },
  { codigo: "971", pais: "Emirados Árabes Unidos" },
  { codigo: "972", pais: "Israel" },
  { codigo: "973", pais: "Bahrein" },
  { codigo: "974", pais: "Catar" },
  { codigo: "975", pais: "Butão" },
  { codigo: "976", pais: "Mongólia" },
  { codigo: "977", pais: "Nepal" },
  { codigo: "992", pais: "Tajiquistão" },
  { codigo: "993", pais: "Turcomenistão" },
  { codigo: "994", pais: "Azerbaijão" },
  { codigo: "995", pais: "Geórgia" },
  { codigo: "996", pais: "Quirguistão" },
  { codigo: "998", pais: "Uzbequistão" },
  { codigo: "1473", pais: "Granada" },
  { codigo: "1758", pais: "Santa Lúcia" },
  { codigo: "1784", pais: "São Vicente e Granadinas" },
  { codigo: "1787", pais: "Porto Rico" },
  { codigo: "1809", pais: "República Dominicana" },
  { codigo: "1868", pais: "Trinidad e Tobago" },
  { codigo: "1869", pais: "São Cristóvão e Névis" },
  { codigo: "1876", pais: "Jamaica" },
];

/**
 * Separa um telefone já salvo em DDI + resto. Dado legado (sem
 * prefixo "+CC ", já que o DDI é novo) cai sempre no default Brasil,
 * mantendo compatibilidade com tudo que já está no banco.
 */
export function extrairDdiENumero(valor?: string | null): { ddi: string; numero: string } {
  const bruto = (valor ?? "").trim();
  const match = bruto.match(/^\+?(\d{1,4})\s+(.+)$/);
  if (match && DDIS.some((d) => d.codigo === match[1])) {
    return { ddi: match[1], numero: match[2] };
  }
  return { ddi: "55", numero: bruto };
}
